### ISSUE TITLE
Cadaguman et al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#4]
**Title:**

Query Mechanism for Medical Appointments Using Enhanced Convolutional Neural Networks

**Members:**

Kezia Mari Cabalonga, Louie Steven Cadaguman, Michael Reyes, Jezreel Zaldarriaga

**Comment by geniusqwerty12** [comment]
Good afternoon, please include the ready to publish manuscript on the docs folder for me to evaluate.

As for your application, I tried to run the exe file and I encounter an error. I also tried to run the jar file via terminal, and an error also occurred. I will include the error logs here.

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: main_interface/QueryMain has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

Here is my jre and jdk version:
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
javac 1.8.0_311

I tried to open and run the source code on VS Code, the GUI opened, but I encountered some errors. For Netbeans I followed your instructions on the manual but Netbeans cannot locate the project.

VS Code error logs:

On App Load
        java.io.FileNotFoundException: datasets\new_Dataset.csv (The system cannot find the path specified)
                at java.io.FileInputStream.open0(Native Method)
                at java.io.FileInputStream.open(FileInputStream.java:195)  
                at java.io.FileInputStream.<init>(FileInputStream.java:138)
                at java.io.FileInputStream.<init>(FileInputStream.java:93)
                at java.io.FileReader.<init>(FileReader.java:58)
                at main_interface.QueryView.<init>(QueryView.java:70)
                at main_interface.QueryMain.<clinit>(QueryMain.java:16)
        java.io.FileNotFoundException: datasets\new_Dataset.csv (The system cannot find the path specified)
                at java.io.FileInputStream.open0(Native Method)
                at java.io.FileInputStream.open(FileInputStream.java:195)
                at java.io.FileInputStream.<init>(FileInputStream.java:138)
                at java.io.FileInputStream.<init>(FileInputStream.java:93)
                at java.io.FileReader.<init>(FileReader.java:58)
                at main_interface.ListView.<init>(ListView.java:67)
                at main_interface.QueryMain.<clinit>(QueryMain.java:18)
        java.io.FileNotFoundException: datasets\new_Dataset.csv (The system cannot find the path specified)
                at java.io.FileInputStream.open0(Native Method)
                at java.io.FileInputStream.open(FileInputStream.java:195)
                at java.io.FileInputStream.<init>(FileInputStream.java:138)
                at java.io.FileInputStream.<init>(FileInputStream.java:93)
                at java.io.FileReader.<init>(FileReader.java:58)
                at main_interface.QueryAppointments.<init>(QueryAppointments.java:68)
                at main_interface.QueryMain.<clinit>(QueryMain.java:19)
        java.io.FileNotFoundException: datasets\new_Dataset.csv (The system cannot find the path specified)
                at java.io.FileInputStream.open0(Native Method)
                at java.io.FileInputStream.open(FileInputStream.java:195)
                at java.io.FileInputStream.<init>(FileInputStream.java:138)
                at java.io.FileInputStream.<init>(FileInputStream.java:93)
                at java.io.FileReader.<init>(FileReader.java:58)
                at main_interface.QueryInbox.<init>(QueryInbox.java:68)
                at main_interface.QueryMain.<clinit>(QueryMain.java:20)

Inputting symptoms
        Storage:
        Storage:
        index 0 javax.swing.JButton[,0,0,150x25,alignmentX=0.0,alignmentY=0.5,border=javax.swing.plaf.BorderUIResource$CompoundBorderUIResource@1e566fb7,flags=296,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=javax.swing.plaf.InsetsUIResource[top=2,left=14,bottom=2,right=14],paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=headache,defaultCapable=true]
        Storage:
        index 0 javax.swing.JButton[,0,0,150x25,alignmentX=0.0,alignmentY=0.5,border=javax.swing.plaf.BorderUIResource$CompoundBorderUIResource@1e566fb7,flags=296,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=javax.swing.plaf.InsetsUIResource[top=2,left=14,bottom=2,right=14],paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=headache,defaultCapable=true]
        index 1 javax.swing.JButton[,150,0,150x25,alignmentX=0.0,alignmentY=0.5,border=javax.swing.plaf.BorderUIResource$CompoundBorderUIResource@1e566fb7,flags=296,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=javax.swing.plaf.InsetsUIResource[top=2,left=14,bottom=2,right=14],paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=cough,defaultCapable=true]
        java.io.FileNotFoundException: config\TestFile.txt (The system cannot find the path specified)

**Comment by geniusqwerty12** [comment]
Upon chatting with Louie, the issue with the exe and jar file not running because of the JDK version incompatibility. The version to be used should be 12 and above.

**Comment by geniusqwerty12** [comment]
The problem with the IDEs (VSCode and NetBeans) were resolved. Please update the user manual to include the following:
Requirements:
Java SDK version 12 and up.

**Comment by lsnine** [comment]
Okay Sir, noted, thanks!

**Comment by geniusqwerty12** [comment]
Good evening sir @mjsolidarios @cictapps, I am waiting for their manuscript to be uploaded on their github repo.

**Comment by geniusqwerty12** [comment]
Good morning sir @mjsolidarios @cictapps, @lsnine uploaded the manuscript which I checked. I found no problems. Giving this to you for finalizing their approval.
